// Ally-5 game generation kernels.
// Each generator emits a complete, runnable lapia_shim Python game —
// these templates ARE the model's training corpus (see packages/ally5-knowledge/).
"use client";

export interface GameParams {
  title: string;
  model: string; // model name shown in the generated header
  playerRGB: [number, number, number];
  enemyRGB: [number, number, number];
  accentRGB: [number, number, number];
  speed: number; // 0.8 .. 1.6
  juice: number; // 0 = nano/fast essentials · 1 = pro · 2 = max/game extra polish
  coins: number; // collectibles count where applicable
}

export type GameType =
  | "snake"
  | "pong"
  | "shooter"
  | "flappy"
  | "breakout"
  | "collect";

export const GAME_LABELS: Record<GameType, string> = {
  snake: "Snake",
  pong: "Pong",
  shooter: "Space Shooter",
  flappy: "Flappy Flier",
  breakout: "Breakout",
  collect: "Coin Collector",
};

const C = (rgb: [number, number, number]) => `Color(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`;

// ---------------------------------------------------------------------------
// SNAKE
// ---------------------------------------------------------------------------
function snakeCode(p: GameParams): string {
  return `"""
${p.title} — Snake · generated by ${p.model}
Controls: arrow keys / WASD · Space restarts after a crash
"""
from lapia_shim import Game, Scene, Vector2, Color, Math

GRID_W, GRID_H = 24, 18
CELL = 32

class SnakeScene(Scene):
    def on_load(self):
        self.bg_color = Color(12, 14, 24)
        self.best = 0
        self.reset()

    def reset(self):
        self.snake = [Vector2(6, 9), Vector2(5, 9), Vector2(4, 9)]
        self.dir = Vector2(1, 0)
        self.next_dir = Vector2(1, 0)
        self.step = 0.0
        self.interval = 0.13 / ${p.speed}
        self.score = 0
        self.dead = False
        self.flash = 0.0
        self.spawn_food()

    def spawn_food(self):
        while True:
            f = Vector2(Math.random_int(1, GRID_W - 2), Math.random_int(1, GRID_H - 2))
            if all(s.x != f.x or s.y != f.y for s in self.snake):
                self.food = f
                return

    def on_update(self, dt):
        inp = self.input
        if self.dead:
            self.flash = max(0.0, self.flash - dt)
            if inp.key_pressed('space') or inp.key_pressed('enter'):
                self.reset()
            return
        if inp.key_pressed('up') or inp.key_pressed('w'):
            if self.dir.y == 0: self.next_dir = Vector2(0, -1)
        elif inp.key_pressed('down') or inp.key_pressed('s'):
            if self.dir.y == 0: self.next_dir = Vector2(0, 1)
        elif inp.key_pressed('left') or inp.key_pressed('a'):
            if self.dir.x == 0: self.next_dir = Vector2(-1, 0)
        elif inp.key_pressed('right') or inp.key_pressed('d'):
            if self.dir.x == 0: self.next_dir = Vector2(1, 0)

        self.step += dt
        if self.step < self.interval:
            return
        self.step = 0.0
        self.dir = self.next_dir
        head = Vector2(self.snake[0].x + self.dir.x, self.snake[0].y + self.dir.y)
        hit_wall = head.x < 0 or head.y < 0 or head.x >= GRID_W or head.y >= GRID_H
        hit_self = any(s.x == head.x and s.y == head.y for s in self.snake)
        if hit_wall or hit_self:
            self.dead = True
            self.flash = 1.0
            self.best = max(self.best, self.score)
            print(f"Game over! Score: {self.score}")
            return
        self.snake.insert(0, head)
        if head.x == self.food.x and head.y == self.food.y:
            self.score += 10
            self.interval = max(0.055, self.interval * 0.982)
            self.spawn_food()
        else:
            self.snake.pop()

    def on_render(self, r):
        # subtle grid
        for gx in range(GRID_W + 1):
            r.draw_line(Vector2(gx * CELL, 0), Vector2(gx * CELL, GRID_H * CELL), Color(255, 255, 255, 7), 1)
        for gy in range(GRID_H + 1):
            r.draw_line(Vector2(0, gy * CELL), Vector2(GRID_W * CELL, gy * CELL), Color(255, 255, 255, 7), 1)
        # food
        r.fill_circle(Vector2(self.food.x * CELL + 16, self.food.y * CELL + 16), 10, ${C(p.enemyRGB)})
        # snake
        n = len(self.snake)
        for i, s in enumerate(self.snake):
            t = 1.0 - i / max(1, n)
            col = Color(${p.playerRGB[0]}, ${p.playerRGB[1]}, ${p.playerRGB[2]}, int(140 + 115 * t))
            r.fill_rect(Vector2(s.x * CELL + 2, s.y * CELL + 2), Vector2(CELL - 4, CELL - 4), col)
        # HUD
        r.draw_text(Vector2(14, 10), f"Score: {self.score}", color=Color(235, 240, 250), size=22)
        r.draw_text(Vector2(14, 36), f"Best: {self.best}", color=Color(150, 158, 180), size=15)
        if self.dead:
            r.fill_rect(Vector2(0, 0), Vector2(GRID_W * CELL, GRID_H * CELL), Color(6, 8, 14, 170))
            r.draw_text(Vector2(GRID_W * 16, GRID_H * 16 - 30), "GAME OVER", color=${C(p.enemyRGB)}, size=44)
            r.draw_text(Vector2(GRID_W * 16, GRID_H * 16 + 12), "Space to try again", color=Color(200, 205, 220), size=18)

game = Game(title="${p.title}", size=(GRID_W * CELL, GRID_H * CELL), fps=60)
game.run(SnakeScene())
`;
}

// ---------------------------------------------------------------------------
// PONG
// ---------------------------------------------------------------------------
function pongCode(p: GameParams): string {
  return `"""
${p.title} — Pong · generated by ${p.model}
Controls: mouse or up/down keys · first to 5 wins
"""
from lapia_shim import Game, Scene, Vector2, Color, Math

W, H = 800, 560
PADDLE_H = 96
WIN_SCORE = 5

class PongScene(Scene):
    def on_load(self):
        self.bg_color = Color(10, 12, 20)
        self.player_y = H / 2
        self.ai_y = H / 2
        self.score_p = 0
        self.score_a = 0
        self.serve(1)

    def serve(self, direction):
        self.ball = Vector2(W / 2, H / 2)
        ang = Math.random_range(-0.6, 0.6)
        spd = 340 * ${p.speed}
        self.vel = Vector2(Math.cos(ang) * direction * spd, Math.sin(ang) * spd)
        self.hits = 0

    def on_update(self, dt):
        inp = self.input
        # player paddle: mouse takes priority, keys as backup
        if inp.mouse_position.y > 1:
            self.player_y = inp.mouse_position.y
        if inp.key_down('up') or inp.key_down('w'): self.player_y -= 420 * dt
        if inp.key_down('down') or inp.key_down('s'): self.player_y += 420 * dt
        self.player_y = Math.clamp(self.player_y, PADDLE_H / 2, H - PADDLE_H / 2)

        # simple AI: track ball with limited speed
        target = self.ball.y
        self.ai_y += Math.clamp(target - self.ai_y, -1, 1) * (250 * ${p.speed}) * dt * (1.0 if self.vel.x > 0 else 0.45)
        self.ai_y = Math.clamp(self.ai_y, PADDLE_H / 2, H - PADDLE_H / 2)

        self.ball += self.vel * dt

        # wall bounces
        if self.ball.y < 10 or self.ball.y > H - 10:
            self.vel.y *= -1
            self.ball.y = Math.clamp(self.ball.y, 10, H - 10)

        # paddle collisions
        if self.vel.x < 0 and self.ball.x < 34 and self.ball.x > 20 and abs(self.ball.y - self.player_y) < PADDLE_H / 2 + 8:
            self.vel.x = abs(self.vel.x) * 1.06
            self.vel.y += (self.ball.y - self.player_y) * 6
            self.hits += 1
        if self.vel.x > 0 and self.ball.x > W - 34 and self.ball.x < W - 20 and abs(self.ball.y - self.ai_y) < PADDLE_H / 2 + 8:
            self.vel.x = -abs(self.vel.x) * 1.06
            self.vel.y += (self.ball.y - self.ai_y) * 6
            self.hits += 1

        # scoring
        if self.ball.x < -10:
            self.score_a += 1; self.serve(1)
        if self.ball.x > W + 10:
            self.score_p += 1; self.serve(-1)

    def on_render(self, r):
        # center dashed line
        for y in range(0, H, 36):
            r.fill_rect(Vector2(W / 2 - 3, y + 6), Vector2(6, 20), Color(255, 255, 255, 36))
        r.fill_rect(Vector2(22, self.player_y - PADDLE_H / 2), Vector2(12, PADDLE_H), ${C(p.playerRGB)})
        r.fill_rect(Vector2(W - 34, self.ai_y - PADDLE_H / 2), Vector2(12, PADDLE_H), ${C(p.enemyRGB)})
        r.fill_circle(self.ball, 8, Color(250, 250, 255))
        r.draw_text(Vector2(W / 2 - 70, 18), str(self.score_p), color=${C(p.playerRGB)}, size=42)
        r.draw_text(Vector2(W / 2 + 44, 18), str(self.score_a), color=${C(p.enemyRGB)}, size=42)
        if self.score_p >= WIN_SCORE or self.score_a >= WIN_SCORE:
            msg = "YOU WIN!" if self.score_p >= WIN_SCORE else "CPU WINS"
            r.fill_rect(Vector2(0, 0), Vector2(W, H), Color(6, 8, 14, 160))
            r.draw_text(Vector2(W / 2, H / 2), msg, color=Color(240, 244, 255), size=48)
            r.draw_text(Vector2(W / 2, H / 2 + 44), "Space for a rematch", color=Color(200, 205, 220), size=18)
            if self.input.key_pressed('space'):
                self.score_p = 0; self.score_a = 0; self.serve(1)

game = Game(title="${p.title}", size=(W, H), fps=60)
game.run(PongScene())
`;
}

// ---------------------------------------------------------------------------
// SPACE SHOOTER
// ---------------------------------------------------------------------------
function shooterCode(p: GameParams): string {
  return `"""
${p.title} — Space Shooter · generated by ${p.model}
Controls: arrow keys / WASD to fly · Space to shoot
"""
from lapia_shim import Game, Scene, Sprite, Vector2, Color, Math

W, H = 800, 600

class ShooterScene(Scene):
    def on_load(self):
        self.bg_color = Color(8, 10, 20)
        self.ship = Vector2(W / 2, H - 80)
        self.bullets = []
        self.enemies = []
        self.stars = []
        for i in range(70):
            self.stars.append({'p': Vector2(Math.random_range(0, W), Math.random_range(0, H)), 's': Math.random_range(20, 90)})
        self.spawn_t = 0.0
        self.cool = 0.0
        self.score = 0
        self.lives = 3
        self.inv = 0.0
        self.over = False
        self.boom = []

    def spawn_enemy(self):
        e = Vector2(Math.random_range(40, W - 40), -30)
        spd = Math.random_range(90, 170) * ${p.speed}
        self.enemies.append({'p': e, 's': spd, 'wob': Math.random_range(0, 6.28)})

    def on_update(self, dt):
        if self.over:
            if self.input.key_pressed('space') or self.input.key_pressed('enter'):
                self.on_load()
            return
        inp = self.input
        mv = Vector2(0, 0)
        if inp.key_down('left') or inp.key_down('a'): mv.x -= 1
        if inp.key_down('right') or inp.key_down('d'): mv.x += 1
        if inp.key_down('up') or inp.key_down('w'): mv.y -= 1
        if inp.key_down('down') or inp.key_down('s'): mv.y += 1
        self.ship += mv.normalized * 340 * dt
        self.ship.x = Math.clamp(self.ship.x, 24, W - 24)
        self.ship.y = Math.clamp(self.ship.y, 40, H - 30)
        self.inv = max(0.0, self.inv - dt)

        self.cool -= dt
        if inp.key_down('space') and self.cool <= 0:
            self.cool = 0.16
            self.bullets.append({'p': Vector2(self.ship.x, self.ship.y - 18), 'v': -620})

        self.spawn_t -= dt
        if self.spawn_t <= 0:
            self.spawn_t = Math.random_range(0.5, 1.1) / ${p.speed}
            self.spawn_enemy()

        for b in self.bullets[:]:
            b['p'].y += b['v'] * dt
            if b['p'].y < -12: self.bullets.remove(b)

        for e in self.enemies[:]:
            e['wob'] += dt * 3
            e['p'].y += e['s'] * dt
            e['p'].x += Math.sin(e['wob']) * 40 * dt
            if e['p'].y > H + 30:
                self.enemies.remove(e); continue
            if e['p'].distance_to(self.ship) < 26 and self.inv <= 0:
                self.enemies.remove(e)
                self.lives -= 1
                self.inv = 1.4
                if self.lives <= 0: self.over = True
                continue
            for b in self.bullets[:]:
                if b['p'].distance_to(e['p']) < 22:
                    self.bullets.remove(b)
                    self.enemies.remove(e)
                    self.score += 100
                    ${p.juice >= 1 ? `for i in range(8):
                        self.boom.append({'p': e['p'].copy(), 'v': Vector2.random(Math.random_range(40, 160)), 't': 0.5})` : ""}
                    break

        ${p.juice >= 1 ? `for b in self.boom[:]:
            b['t'] -= dt
            b['p'] += b['v'] * dt
            if b['t'] <= 0: self.boom.remove(b)

        for s in self.stars:
            s['p'].y += s['s'] * dt
            if s['p'].y > H: s['p'].y = 0; s['p'].x = Math.random_range(0, W)` : ""}

    def on_render(self, r):
        ${p.juice >= 1 ? `for s in self.stars:
            a = int(40 + s['s'] / 2)
            r.fill_circle(s['p'], 1.4, Color(220, 228, 255, a))
        for b in self.boom:
            r.fill_circle(b['p'], 3 + b['t'] * 6, Color(255, 170, 80, int(b['t'] * 300)))
` : `        pass
`}
        # ship (triangle-ish)
        r.fill_rect(Vector2(self.ship.x - 3, self.ship.y - 20), Vector2(6, 40), ${C(p.playerRGB)})
        r.fill_rect(Vector2(self.ship.x - 14, self.ship.y + 6), Vector2(28, 8), ${C(p.playerRGB)})
        if self.inv <= 0 or int(self.inv * 12) % 2 == 0:
            r.fill_circle(Vector2(self.ship.x, self.ship.y - 6), 9, Color(230, 240, 255))
        for b in self.bullets:
            r.fill_rect(Vector2(b['p'].x - 2, b['p'].y - 10), Vector2(4, 14), ${C(p.accentRGB)})
        for e in self.enemies:
            r.fill_rect(Vector2(e['p'].x - 14, e['p'].y - 14), Vector2(28, 28), ${C(p.enemyRGB)})
            r.fill_circle(e['p'], 6, Color(20, 24, 34))
        r.draw_text(Vector2(16, 12), f"Score: {self.score}", color=Color(235, 240, 250), size=22)
        r.draw_text(Vector2(W - 120, 12), "Lives: " + str(self.lives), color=${C(p.enemyRGB)}, size=22)
        if self.over:
            r.fill_rect(Vector2(0, 0), Vector2(W, H), Color(6, 8, 14, 170))
            r.draw_text(Vector2(W / 2, H / 2 - 20), "SHIP DOWN", color=${C(p.enemyRGB)}, size=48)
            r.draw_text(Vector2(W / 2, H / 2 + 26), f"Score {self.score} · Space to fly again", color=Color(200, 205, 220), size=18)

game = Game(title="${p.title}", size=(W, H), fps=60)
game.run(ShooterScene())
`;
}

// ---------------------------------------------------------------------------
// FLAPPY
// ---------------------------------------------------------------------------
function flappyCode(p: GameParams): string {
  return `"""
${p.title} — Flappy Flier · generated by ${p.model}
Controls: Space / click to flap
"""
from lapia_shim import Game, Scene, Vector2, Color, Math

W, H = 720, 600
GAP = 190
PIPE_W = 70

class FlappyScene(Scene):
    def on_load(self):
        self.bg_color = Color(16, 20, 34)
        self.bird = Vector2(200, H / 2)
        self.vel = 0.0
        self.pipes = []
        self.scroll = 0.0
        self.spacing = 250 / ${p.speed}
        self.started = False
        self.dead = False
        self.score = 0
        self.best = 0
        for i in range(3):
            self.add_pipe(W + 150 + i * self.spacing)

    def add_pipe(self, x):
        gap_y = Math.random_range(140, H - 140)
        self.pipes.append({'x': x, 'gap_y': gap_y, 'passed': False})

    def flap(self):
        if self.dead:
            self.on_load()
            return
        self.started = True
        self.vel = -330

    def on_update(self, dt):
        if self.input.key_pressed('space') or self.input.mouse_pressed(1):
            self.flap()
        if self.dead or not self.started:
            return
        self.vel += 900 * dt
        self.bird.y += self.vel * dt

        for pipe in self.pipes:
            pipe['x'] -= 160 * ${p.speed} * dt
        if self.pipes and self.pipes[0]['x'] < -PIPE_W - 10:
            self.pipes.pop(0)
        if self.pipes and self.pipes[-1]['x'] < W:
            self.add_pipe(self.pipes[-1]['x'] + self.spacing)

        for pipe in self.pipes:
            if not pipe['passed'] and pipe['x'] + PIPE_W < self.bird.x:
                pipe['passed'] = True
                self.score += 1
                if self.score > self.best: self.best = self.score

        # collisions
        if self.bird.y > H - 24 or self.bird.y < -20:
            self.dead = True
            print(f"Crashed! Score: {self.score}")
        for pipe in self.pipes:
            if abs(pipe['x'] + PIPE_W / 2 - self.bird.x) < PIPE_W / 2 + 14:
                if abs(self.bird.y - pipe['gap_y']) > GAP / 2 - 8:
                    self.dead = True

    def on_render(self, r):
        ${p.juice >= 1 ? `# parallax hills
        r.fill_rect(Vector2(0, H - 46), Vector2(W, 46), Color(24, 30, 48))
        for i in range(0, W + 60, 60):
            x = (i - (self.scroll if hasattr(self, 'scroll') else 0)) % (W + 60)
            r.fill_circle(Vector2(x, H - 40), 26, Color(26, 33, 54))
` : ""}
        for pipe in self.pipes:
            top_h = pipe['gap_y'] - GAP / 2
            bot_y = pipe['gap_y'] + GAP / 2
            r.fill_rect(Vector2(pipe['x'], 0), Vector2(PIPE_W, top_h), ${C(p.accentRGB)})
            r.fill_rect(Vector2(pipe['x'] - 5, top_h - 20), Vector2(PIPE_W + 10, 20), ${C(p.accentRGB)})
            r.fill_rect(Vector2(pipe['x'], bot_y), Vector2(PIPE_W, H - bot_y), ${C(p.accentRGB)})
            r.fill_rect(Vector2(pipe['x'] - 5, bot_y), Vector2(PIPE_W + 10, 20), ${C(p.accentRGB)})
        # bird
        r.fill_circle(self.bird, 14, ${C(p.playerRGB)})
        r.fill_circle(Vector2(self.bird.x + 6, self.bird.y - 4), 4, Color(20, 22, 30))
        r.draw_text(Vector2(W / 2, 40), str(self.score), color=Color(240, 244, 255), size=52)
        r.draw_text(Vector2(W / 2, 92), f"Best: {self.best}", color=Color(150, 158, 180), size=16)
        if not self.started and not self.dead:
            r.draw_text(Vector2(W / 2, H / 2 + 90), "Space or click to start", color=Color(200, 205, 220), size=20)
        if self.dead:
            r.fill_rect(Vector2(0, 0), Vector2(W, H), Color(6, 8, 14, 150))
            r.draw_text(Vector2(W / 2, H / 2 - 16), "SPLAT!", color=${C(p.enemyRGB)}, size=52)
            r.draw_text(Vector2(W / 2, H / 2 + 34), "Space to fly again", color=Color(200, 205, 220), size=18)

game = Game(title="${p.title}", size=(W, H), fps=60)
game.run(FlappyScene())
`;
}

// ---------------------------------------------------------------------------
// BREAKOUT
// ---------------------------------------------------------------------------
function breakoutCode(p: GameParams): string {
  return `"""
${p.title} — Breakout · generated by ${p.model}
Controls: mouse or arrow keys · clears bricks to win
"""
from lapia_shim import Game, Scene, Vector2, Color, Math

W, H = 800, 600
COLS, ROWS = 10, 6
BW, BH = 72, 24

class BreakoutScene(Scene):
    def on_load(self):
        self.bg_color = Color(12, 13, 22)
        self.paddle = W / 2
        self.bricks = []
        for row in range(ROWS):
            for col in range(COLS):
                self.bricks.append({'x': 13 + col * (BW + 6), 'y': 60 + row * (BH + 8), 'row': row})
        self.reset_ball()
        self.score = 0
        self.lives = 3
        self.won = False
        self.over = False

    def reset_ball(self):
        self.ball = Vector2(W / 2, H - 90)
        ang = Math.random_range(-0.5, 0.5) - 1.57
        self.vel = Vector2(Math.cos(ang), Math.sin(ang)) * (330 * ${p.speed})

    def on_update(self, dt):
        if self.over or self.won:
            if self.input.key_pressed('space'):
                self.on_load()
            return
        inp = self.input
        if inp.mouse_position.x > 1: self.paddle = inp.mouse_position.x
        if inp.key_down('left') or inp.key_down('a'): self.paddle -= 480 * dt
        if inp.key_down('right') or inp.key_down('d'): self.paddle += 480 * dt
        self.paddle = Math.clamp(self.paddle, 60, W - 60)

        self.ball += self.vel * dt
        if self.ball.x < 10 or self.ball.x > W - 10:
            self.vel.x *= -1; self.ball.x = Math.clamp(self.ball.x, 10, W - 10)
        if self.ball.y < 10:
            self.vel.y *= -1; self.ball.y = 10
        if self.ball.y > H + 16:
            self.lives -= 1
            if self.lives <= 0: self.over = True
            else: self.reset_ball()

        # paddle bounce
        if self.vel.y > 0 and self.ball.y > H - 42 and self.ball.y < H - 26 and abs(self.ball.x - self.paddle) < 62:
            self.vel.y = -abs(self.vel.y) * 1.03
            self.vel.x += (self.ball.x - self.paddle) * 5

        # bricks
        for b in self.bricks[:]:
            if abs(self.ball.x - (b['x'] + BW / 2)) < BW / 2 + 7 and abs(self.ball.y - (b['y'] + BH / 2)) < BH / 2 + 7:
                self.bricks.remove(b)
                self.vel.y *= -1
                self.score += (ROWS - b['row']) * 10
                break
        if not self.bricks:
            self.won = True

    def on_render(self, r):
        for b in self.bricks:
            shade = 200 - b['row'] * 22
            r.fill_rect(Vector2(b['x'], b['y']), Vector2(BW, BH), Color(${p.accentRGB[0]}, ${p.accentRGB[1]}, ${p.accentRGB[2]}, shade))
        r.fill_rect(Vector2(self.paddle - 60, H - 34), Vector2(120, 14), ${C(p.playerRGB)})
        r.fill_circle(self.ball, 8, Color(250, 250, 255))
        r.draw_text(Vector2(16, 12), f"Score: {self.score}", color=Color(235, 240, 250), size=22)
        r.draw_text(Vector2(W - 120, 12), "Lives: " + str(self.lives), color=${C(p.enemyRGB)}, size=22)
        if self.won:
            r.fill_rect(Vector2(0, 0), Vector2(W, H), Color(6, 8, 14, 160))
            r.draw_text(Vector2(W / 2, H / 2 - 16), "BOARD CLEARED!", color=${C(p.accentRGB)}, size=44)
            r.draw_text(Vector2(W / 2, H / 2 + 30), "Space to play again", color=Color(200, 205, 220), size=18)
        if self.over:
            r.fill_rect(Vector2(0, 0), Vector2(W, H), Color(6, 8, 14, 170))
            r.draw_text(Vector2(W / 2, H / 2 - 16), "GAME OVER", color=${C(p.enemyRGB)}, size=48)
            r.draw_text(Vector2(W / 2, H / 2 + 30), "Space to retry", color=Color(200, 205, 220), size=18)

game = Game(title="${p.title}", size=(W, H), fps=60)
game.run(BreakoutScene())
`;
}

// ---------------------------------------------------------------------------
// TOP-DOWN COIN COLLECTOR (showcases real sprite assets via load_image)
// ---------------------------------------------------------------------------
function collectCode(p: GameParams): string {
  return `"""
${p.title} — Coin Collector · generated by ${p.model}
Controls: WASD / arrow keys · grab the loot before the timer ends
Real sprite assets are loaded from the toolbox with load_image().
"""
from lapia_shim import Game, Scene, Sprite, Vector2, Color, Math, load_image

W, H = 800, 576
TIME_LIMIT = 45

class CollectScene(Scene):
    def on_load(self):
        self.bg_color = Color(14, 18, 28)
        self.player = Sprite(image=load_image("sprites/player/knight.png"), size=(36, 36))
        self.player.position = Vector2(W / 2, H / 2)
        self.coins = []
        for i in range(${p.coins}):
            s = Sprite(image=load_image("sprites/coins/coin_gold.png"), size=(22, 22))
            s.position = Vector2(Math.random_range(40, W - 40), Math.random_range(40, H - 40))
            self.coins.append({'s': s, 'got': False, 't': Math.random_range(0, 6.28)})
        self.ghost = Sprite(image=load_image("sprites/enemies/slime_green.png"), size=(34, 34))
        self.ghost.position = Vector2(60, 60)
        self.ghost_dir = Vector2(1, 0.4)
        self.score = 0
        self.timer = TIME_LIMIT
        self.over = False
        self.win = False

    def on_update(self, dt):
        if self.over:
            if self.input.key_pressed('space') or self.input.key_pressed('enter'):
                self.on_load()
            return
        inp = self.input
        mv = Vector2(0, 0)
        if inp.key_down('w') or inp.key_down('up'): mv.y -= 1
        if inp.key_down('s') or inp.key_down('down'): mv.y += 1
        if inp.key_down('a') or inp.key_down('left'): mv.x -= 1
        if inp.key_down('d') or inp.key_down('right'): mv.x += 1
        self.player.position += mv.normalized * (250 * ${p.speed}) * dt
        self.player.position.x = Math.clamp(self.player.position.x, 18, W - 18)
        self.player.position.y = Math.clamp(self.player.position.y, 18, H - 18)
        if mv.x != 0:
            self.player.flip_x = mv.x < 0

        for c in self.coins:
            if c['got']: continue
            c['t'] += dt
            c['s'].position = Vector2(c['s'].position.x, c['s'].position.y + Math.sin(c['t'] * 3) * 0.6)
            if c['s'].position.distance_to(self.player.position) < 26:
                c['got'] = True
                c['s'].visible = False
                self.score += 10

        # wandering slime chases slowly
        to_player = self.player.position - self.ghost.position
        self.ghost_dir = (self.ghost_dir + to_player.normalized * 0.6 * dt).normalized
        self.ghost.position += self.ghost_dir * (95 * ${p.speed}) * dt
        if self.ghost.position.distance_to(self.player.position) < 28:
            self.over = True
            print("The slime got you!")

        self.timer -= dt
        if self.timer <= 0:
            self.over = True
            self.win = self.score >= ${p.coins} * 10 / 2

    def on_render(self, r):
        # checker floor
        for gy in range(0, H // 32 + 1):
            for gx in range(0, W // 32 + 1):
                if (gx + gy) % 2 == 0:
                    r.fill_rect(Vector2(gx * 32, gy * 32), Vector2(32, 32), Color(255, 255, 255, 6))
        for c in self.coins:
            if not c['got']:
                c['s'].render(r.surface, self.camera)
        self.ghost.render(r.surface, self.camera)
        self.player.render(r.surface, self.camera)
        r.draw_text(Vector2(16, 12), f"Score: {self.score}", color=Color(235, 240, 250), size=22)
        r.draw_text(Vector2(W - 150, 12), f"Time: {int(self.timer)}s", color=${C(p.accentRGB)}, size=22)
        if self.over:
            r.fill_rect(Vector2(0, 0), Vector2(W, H), Color(6, 8, 14, 170))
            msg = "TIME UP — NICE LOOT!" if self.win else "CAUGHT!"
            r.draw_text(Vector2(W / 2, H / 2 - 16), msg, color=${C(p.accentRGB)} if self.win else ${C(p.enemyRGB)}, size=40)
            r.draw_text(Vector2(W / 2, H / 2 + 30), f"Score {self.score} · Space to replay", color=Color(200, 205, 220), size=18)

game = Game(title="${p.title}", size=(W, H), fps=60)
game.run(CollectScene())
`;
}

export const GAME_GENERATORS: Record<GameType, (p: GameParams) => string> = {
  snake: snakeCode,
  pong: pongCode,
  shooter: shooterCode,
  flappy: flappyCode,
  breakout: breakoutCode,
  collect: collectCode,
};

export function generateGame(type: GameType, p: GameParams): string {
  return GAME_GENERATORS[type](p);
}
