"""
lapia-engine :: ally_game_kernels
Compact Python port of the Ally-5 game kernels (subset).
The full trained corpus ships with the `ally-kernel` package; the browser
studio version lives in src/lib/ally5-games.ts.
"""
import math

HEADER = '''"""
{title} — {game} · generated by Ally-5
Built by the Ally-5 kernel for the Lapia engine.
"""
from lapia_shim import Game, Scene, Sprite, Vector2, Color, Math, load_image
import math
'''


def generate_game(game: str, title="My Game", model="Ally-5", speed=1.0, **kw) -> str:
    if game == "snake":
        return HEADER.format(title=title, game="Snake") + f'''
GRID_W, GRID_H = 24, 18
CELL = 32

class SnakeScene(Scene):
    def on_load(self):
        self.bg_color = Color(12, 14, 24)
        self.reset()

    def reset(self):
        self.snake = [Vector2(6, 9), Vector2(5, 9), Vector2(4, 9)]
        self.dir = Vector2(1, 0); self.next_dir = Vector2(1, 0)
        self.step = 0.0; self.interval = 0.13 / {speed}
        self.score = 0; self.dead = False
        self.spawn_food()

    def spawn_food(self):
        while True:
            f = Vector2(Math.random_int(1, GRID_W - 2), Math.random_int(1, GRID_H - 2))
            if all(s.x != f.x or s.y != f.y for s in self.snake):
                self.food = f; return

    def on_update(self, dt):
        inp = self.input
        if self.dead:
            if inp.key_pressed('space'): self.reset()
            return
        if inp.key_pressed('up') and self.dir.y == 0: self.next_dir = Vector2(0, -1)
        if inp.key_pressed('down') and self.dir.y == 0: self.next_dir = Vector2(0, 1)
        if inp.key_pressed('left') and self.dir.x == 0: self.next_dir = Vector2(-1, 0)
        if inp.key_pressed('right') and self.dir.x == 0: self.next_dir = Vector2(1, 0)
        self.step += dt
        if self.step < self.interval: return
        self.step = 0.0
        self.dir = self.next_dir
        head = Vector2(self.snake[0].x + self.dir.x, self.snake[0].y + self.dir.y)
        if head.x < 0 or head.y < 0 or head.x >= GRID_W or head.y >= GRID_H \
           or any(s.x == head.x and s.y == head.y for s in self.snake):
            self.dead = True
            print(f"Game over! Score: {{self.score}}")
            return
        self.snake.insert(0, head)
        if head.x == self.food.x and head.y == self.food.y:
            self.score += 10; self.interval = max(0.055, self.interval * 0.982); self.spawn_food()
        else:
            self.snake.pop()

    def on_render(self, r):
        for i, s in enumerate(self.snake):
            t = 1.0 - i / max(1, len(self.snake))
            r.fill_rect(Vector2(s.x * CELL + 2, s.y * CELL + 2), Vector2(CELL - 4, CELL - 4),
                        Color(86, 180, 240, int(140 + 115 * t)))
        r.fill_circle(Vector2(self.food.x * CELL + 16, self.food.y * CELL + 16), 10, Color(235, 87, 110))
        r.draw_text(Vector2(14, 10), f"Score: {{self.score}}", color=Color(235, 240, 250), size=22)
        if self.dead:
            r.draw_text(Vector2(GRID_W * 16, GRID_H * 16 - 16), "GAME OVER", color=Color(235, 87, 110), size=44)

game = Game(title="{title}", size=(GRID_W * CELL, GRID_H * CELL), fps=60)
game.run(SnakeScene())
'''
    if game == "pong":
        return HEADER.format(title=title, game="Pong") + f'''
W, H = 800, 560
PH = 96

class PongScene(Scene):
    def on_load(self):
        self.py_ = H / 2; self.ay = H / 2
        self.sp = 0; self.sa = 0
        self.serve(1)

    def serve(self, d):
        self.ball = Vector2(W / 2, H / 2)
        a = Math.random_range(-0.6, 0.6)
        self.vel = Vector2(Math.cos(a) * d * 340, Math.sin(a) * 340)

    def on_update(self, dt):
        if self.input.mouse_position.y > 1: self.py_ = self.input.mouse_position.y
        if self.input.key_down('up'): self.py_ -= 420 * dt
        if self.input.key_down('down'): self.py_ += 420 * dt
        self.py_ = Math.clamp(self.py_, PH / 2, H - PH / 2)
        self.ay += Math.clamp(self.ball.y - self.ay, -1, 1) * 250 * dt
        self.ay = Math.clamp(self.ay, PH / 2, H - PH / 2)
        self.ball += self.vel * dt
        if self.ball.y < 10 or self.ball.y > H - 10: self.vel.y *= -1
        if self.vel.x < 0 and self.ball.x < 34 and abs(self.ball.y - self.py_) < PH / 2 + 8:
            self.vel.x = abs(self.vel.x) * 1.06; self.vel.y += (self.ball.y - self.py_) * 6
        if self.vel.x > 0 and self.ball.x > W - 34 and abs(self.ball.y - self.ay) < PH / 2 + 8:
            self.vel.x = -abs(self.vel.x) * 1.06; self.vel.y += (self.ball.y - self.ay) * 6
        if self.ball.x < -10: self.sa += 1; self.serve(1)
        if self.ball.x > W + 10: self.sp += 1; self.serve(-1)

    def on_render(self, r):
        r.fill_rect(Vector2(22, self.py_ - PH / 2), Vector2(12, PH), Color(86, 180, 240))
        r.fill_rect(Vector2(W - 34, self.ay - PH / 2), Vector2(12, PH), Color(235, 87, 110))
        r.fill_circle(self.ball, 8, Color(250, 250, 255))
        r.draw_text(Vector2(W / 2 - 70, 18), str(self.sp), color=Color(86, 180, 240), size=42)
        r.draw_text(Vector2(W / 2 + 44, 18), str(self.sa), color=Color(235, 87, 110), size=42)

game = Game(title="{title}", size=(W, H), fps=60)
game.run(PongScene())
'''
    # default: coin collector
    return HEADER.format(title=title, game="Coin Collector") + f'''
W, H = 800, 576

class CollectScene(Scene):
    def on_load(self):
        self.bg_color = Color(14, 18, 28)
        self.player = Sprite(color=Color(86, 180, 240), size=(32, 32))
        self.player.position = Vector2(W / 2, H / 2)
        self.coins = []
        for i in range(10):
            s = Sprite(color=Color(250, 204, 21), size=(18, 18))
            s.position = Vector2(Math.random_range(40, W - 40), Math.random_range(40, H - 40))
            self.coins.append(s)
        self.score = 0

    def on_update(self, dt):
        mv = Vector2(0, 0)
        if self.input.key_down('w'): mv.y -= 1
        if self.input.key_down('s'): mv.y += 1
        if self.input.key_down('a'): mv.x -= 1
        if self.input.key_down('d'): mv.x += 1
        self.player.position += mv.normalized * 250 * dt
        for s in self.coins[:]:
            if s.position.distance_to(self.player.position) < 26:
                self.coins.remove(s); self.score += 10
                print(f"Coin! Score: {{self.score}}")

    def on_render(self, r):
        for s in self.coins: s.render(r.surface, self.camera)
        self.player.render(r.surface, self.camera)
        r.draw_text(Vector2(16, 12), f"Score: {{self.score}}", color=Color(235, 240, 250), size=22)

game = Game(title="{title}", size=(W, H), fps=60)
game.run(CollectScene())
'''
