"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { useStudio } from "@/lib/studio-store";
import { toast } from "sonner";
import {
  Send, Gamepad2, Zap, Github, Globe, Download, Check, ArrowRight,
} from "lucide-react";

const TARGETS = [
  {
    id: "itchio", name: "itch.io", icon: Gamepad2, color: "#fa5c5c",
    description: "Free indie game hosting. Best for game jams.",
    steps: [
      "Click 'Build HTML5' below to generate a playable .zip",
      "Download the .zip to your computer",
      "Go to itch.io/upload",
      "Set kind to 'HTML' and upload your .zip",
      "Set viewport dimensions and click 'Save & view'",
    ],
    url: "https://itch.io/upload",
  },
  {
    id: "crazygames", name: "Crazy Games", icon: Zap, color: "#fb923c",
    description: "Web game portal with revenue share.",
    steps: [
      "Click 'Build HTML5' below",
      "Download the .zip",
      "Sign up at developer.crazygames.com",
      "Click 'Submit a Game' and upload",
      "Wait 2-5 business days for review",
    ],
    url: "https://developer.crazygames.com",
  },
  {
    id: "github", name: "GitHub Pages", icon: Github, color: "#94a3b8",
    description: "Free hosting from your GitHub repo.",
    steps: [
      "Click 'Build HTML5' below",
      "Commit the build/ folder to a gh-pages branch",
      "Go to repo Settings > Pages",
      "Set source to 'gh-pages branch'",
      "Game is live at username.github.io/repo-name",
    ],
    url: "https://github.com/gefrus112/lapia-ai-agent/settings/pages",
  },
  {
    id: "html5", name: "HTML5 Standalone", icon: Globe, color: "#3b82f6",
    description: "Self-contained .zip you can host anywhere.",
    steps: [
      "Click 'Build HTML5' below",
      "A single index.html + assets are generated",
      "Test locally by opening index.html in browser",
      "Upload to any static host (Netlify, Vercel, S3)",
      "Share the URL with players",
    ],
    url: "#",
  },
];

export function PublishDialog() {
  const { publishDialogOpen, setPublishDialogOpen, engineKind } = useStudio();
  const [activeTarget, setActiveTarget] = useState<string | null>(null);

  const handleBuildHTML5 = () => {
    // Generate a placeholder HTML5 build (in production this would actually package the game)
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>All In One Engine — Game</title>
<style>
  body { margin: 0; background: #0a0b0e; color: #fff; font-family: system-ui, sans-serif; display: flex; align-items: center; justify-content: center; min-height: 100vh; }
  canvas { background: #1a1d24; image-rendering: pixelated; box-shadow: 0 8px 32px rgba(0,0,0,0.6); }
  .hud { position: fixed; top: 10px; left: 10px; padding: 8px 12px; background: rgba(0,0,0,0.5); border-radius: 4px; font-size: 12px; }
</style>
</head>
<body>
<div class="hud">All In One Engine — ${engineKind}</div>
<canvas id="game" width="800" height="600"></canvas>
<script>
  // Auto-generated by All In One Engine
  // Replace this with your actual game code
  const canvas = document.getElementById('game');
  const ctx = canvas.getContext('2d');
  let x = 100, y = 300;
  const keys = {};
  window.addEventListener('keydown', e => keys[e.key.toLowerCase()] = true);
  window.addEventListener('keyup', e => keys[e.key.toLowerCase()] = false);
  function loop() {
    ctx.fillStyle = '#1a1d24';
    ctx.fillRect(0, 0, 800, 600);
    if (keys['arrowleft'] || keys['a']) x -= 5;
    if (keys['arrowright'] || keys['d']) x += 5;
    if (keys['arrowup'] || keys['w']) y -= 5;
    if (keys['arrowdown'] || keys['s']) y += 5;
    ctx.fillStyle = '#3b82f6';
    ctx.fillRect(x - 16, y - 16, 32, 32);
    requestAnimationFrame(loop);
  }
  loop();
</script>
</body>
</html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "game.html";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Built HTML5 game — game.html downloaded", {
      description: "Upload this to itch.io, Crazy Games, or any static host.",
    });
  };

  const selectedTarget = TARGETS.find(t => t.id === activeTarget);

  return (
    <Dialog open={publishDialogOpen} onOpenChange={setPublishDialogOpen}>
      <DialogContent className="max-w-3xl bg-card border-border max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Send className="w-4 h-4" />
            Publish Your Game
          </DialogTitle>
          <DialogDescription>
            Build your game once, publish to itch.io, Crazy Games, GitHub Pages, or standalone HTML5.
            Click "Build HTML5" first, then follow the platform-specific steps.
          </DialogDescription>
        </DialogHeader>

        {/* Build button */}
        <div className="rounded-lg border border-cyan-500/30 bg-cyan-500/5 p-4 mb-4">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="font-semibold mb-1">Step 1: Build HTML5</h3>
              <p className="text-xs text-muted-foreground">Generate a single .html file that contains your game. ~10KB.</p>
            </div>
            <Button onClick={handleBuildHTML5} size="sm">
              <Download className="w-4 h-4 mr-1" />
              Build HTML5
            </Button>
          </div>
        </div>

        {/* Step 2: Pick platform */}
        <h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">Step 2: Pick a platform</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2 mb-4">
          {TARGETS.map((t) => (
            <button
              key={t.id}
              onClick={() => setActiveTarget(t.id)}
              className={`p-3 rounded-lg border-2 transition-all text-left ${activeTarget === t.id ? "border-cyan-500 bg-cyan-500/10" : "border-border hover:border-muted-foreground"}`}
            >
              <t.icon className="w-5 h-5 mb-2" style={{ color: t.color }} />
              <div className="text-sm font-medium">{t.name}</div>
              <div className="text-[10px] text-muted-foreground mt-1">{t.description}</div>
            </button>
          ))}
        </div>

        {/* Selected platform steps */}
        {selectedTarget && (
          <div className="rounded-lg border border-border bg-background/40 p-4">
            <h4 className="font-semibold mb-3 flex items-center gap-2">
              <selectedTarget.icon className="w-4 h-4" style={{ color: selectedTarget.color }} />
              Publishing to {selectedTarget.name}
            </h4>
            <ol className="space-y-2 mb-4">
              {selectedTarget.steps.map((step, i) => (
                <li key={i} className="flex gap-3 text-xs">
                  <span className="flex-shrink-0 w-5 h-5 rounded-full bg-cyan-500/20 text-cyan-400 flex items-center justify-center font-medium">
                    {i + 1}
                  </span>
                  <span className="text-muted-foreground pt-0.5">{step}</span>
                </li>
              ))}
            </ol>
            {selectedTarget.url !== "#" && (
              <a
                href={selectedTarget.url}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1 text-xs text-cyan-400 hover:text-cyan-300"
              >
                Open {selectedTarget.name} <ArrowRight className="w-3 h-3" />
              </a>
            )}
          </div>
        )}

        {/* Tips */}
        <div className="rounded-lg bg-amber-500/10 border border-amber-500/30 p-4">
          <h4 className="font-semibold mb-2 text-amber-200 text-sm flex items-center gap-2">
            <Check className="w-4 h-4" />
            Tips for getting featured
          </h4>
          <ul className="space-y-1 text-xs text-amber-100/80">
            <li>• Add screenshots and a gameplay video to your listing</li>
            <li>• Write a clear description and use good tags</li>
            <li>• Test on Chrome, Firefox, and Safari before publishing</li>
            <li>• Add mobile touch controls for broader reach</li>
            <li>• Share on social media with #AllInOneEngine</li>
          </ul>
        </div>
      </DialogContent>
    </Dialog>
  );
}
